// <auto-generated />
using eStore.Data;
using eStore.Domain.PagamentoContext;
using eStore.Domain.ProdutoContext;
using eStore.Domain.UsuarioContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace eStore.Data.Migrations
{
    [DbContext(typeof(eStoreContext))]
    [Migration("20180320005332_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eStore.Domain.CarrinhoContext.Carrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("UsuarioId");

                    b.Property<double>("ValorTotal");

                    b.HasKey("Id");

                    b.ToTable("Carrinho");
                });

            modelBuilder.Entity("eStore.Domain.CarrinhoContext.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CarrinhoId");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.ToTable("CarrinhoItem");
                });

            modelBuilder.Entity("eStore.Domain.PagamentoContext.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Forma");

                    b.Property<int>("QuantidadeParcelas");

                    b.Property<int>("Status");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("eStore.Domain.PedidoContext.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PedidoId");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.ToTable("PedidoItem");
                });

            modelBuilder.Entity("eStore.Domain.ProdutoContext.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Categoria");

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.Property<double>("ValorUnitario");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("eStore.Domain.UsuarioContext.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<DateTime>("Nascimento");

                    b.Property<int>("Perfil");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("eStore.Domain.PagamentoContext.Pagamento", b =>
                {
                    b.OwnsOne("eStore.Domain.Endereco", "EnderecoCobranca", b1 =>
                        {
                            b1.Property<Guid?>("PagamentoId");

                            b1.Property<string>("Bairro")
                                .HasColumnName("Bairro");

                            b1.Property<string>("CEP")
                                .HasColumnName("CEP");

                            b1.Property<string>("Complemento")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Logradouro")
                                .HasColumnName("Logradouro");

                            b1.Property<int>("Numero")
                                .HasColumnName("Numero");

                            b1.ToTable("Pagamento");

                            b1.HasOne("eStore.Domain.PagamentoContext.Pagamento")
                                .WithOne("EnderecoCobranca")
                                .HasForeignKey("eStore.Domain.Endereco", "PagamentoId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("eStore.Domain.CidadeUf", "Cidade", b2 =>
                                {
                                    b2.Property<Guid?>("EnderecoPagamentoId");

                                    b2.Property<string>("Nome")
                                        .HasColumnName("Cidade");

                                    b2.Property<string>("UF")
                                        .HasColumnName("UF");

                                    b2.ToTable("Pagamento");

                                    b2.HasOne("eStore.Domain.Endereco")
                                        .WithOne("Cidade")
                                        .HasForeignKey("eStore.Domain.CidadeUf", "EnderecoPagamentoId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });

            modelBuilder.Entity("eStore.Domain.ProdutoContext.Produto", b =>
                {
                    b.OwnsOne("eStore.Domain.ProdutoContext.Dimensao", "Dimensao", b1 =>
                        {
                            b1.Property<Guid>("ProdutoId");

                            b1.Property<double>("Altura")
                                .HasColumnName("Altura");

                            b1.Property<double>("Largura")
                                .HasColumnName("Largura");

                            b1.Property<double>("Peso")
                                .HasColumnName("Peso");

                            b1.Property<double>("Profundidade")
                                .HasColumnName("Profundidade");

                            b1.ToTable("Produto");

                            b1.HasOne("eStore.Domain.ProdutoContext.Produto")
                                .WithOne("Dimensao")
                                .HasForeignKey("eStore.Domain.ProdutoContext.Dimensao", "ProdutoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("eStore.Domain.UsuarioContext.Usuario", b =>
                {
                    b.OwnsOne("eStore.Domain.Endereco", "EnderecoResidencial", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId");

                            b1.Property<string>("Bairro")
                                .HasColumnName("Bairro");

                            b1.Property<string>("CEP")
                                .HasColumnName("CEP");

                            b1.Property<string>("Complemento")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Logradouro")
                                .HasColumnName("Logradouro");

                            b1.Property<int>("Numero")
                                .HasColumnName("Numero");

                            b1.ToTable("Usuario");

                            b1.HasOne("eStore.Domain.UsuarioContext.Usuario")
                                .WithOne("EnderecoResidencial")
                                .HasForeignKey("eStore.Domain.Endereco", "UsuarioId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("eStore.Domain.CidadeUf", "Cidade", b2 =>
                                {
                                    b2.Property<Guid>("EnderecoUsuarioId");

                                    b2.Property<string>("Nome")
                                        .HasColumnName("Cidade");

                                    b2.Property<string>("UF")
                                        .HasColumnName("UF");

                                    b2.ToTable("Usuario");

                                    b2.HasOne("eStore.Domain.Endereco")
                                        .WithOne("Cidade")
                                        .HasForeignKey("eStore.Domain.CidadeUf", "EnderecoUsuarioId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsOne("eStore.Domain.NomeCompleto", "Nome", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId");

                            b1.Property<string>("Nome");

                            b1.Property<string>("Sobrenome");

                            b1.ToTable("Usuario");

                            b1.HasOne("eStore.Domain.UsuarioContext.Usuario")
                                .WithOne("Nome")
                                .HasForeignKey("eStore.Domain.NomeCompleto", "UsuarioId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
